### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by darosior** [LeonodTeam/bitcoin-lyon#1]
Experts et passionés, => Experts et passionnés,

**Comment by adct3d** [comment]
Page achat de bitcoin, rubrique en ligne : Nous pouvons vous enoyer les bitcoins on-chain ou via Lightning
=> enVoyer

**Comment by darosior** [comment]
Remove Hugo tags in 404.html

**Comment by darosior** [comment]
Faute d'orthographe
> Nous pouvons vous envoyer les bitconins au-travers d'un coinjoin

Changer le carousel pour mettre international en dernier / dispo à Lyon en premier
